# Generated by Django 4.2.7 on 2023-12-03 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Sucursales', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Sucursales.sucursal')),
                ('country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'direcciones',
                'managed': False,
            },
        ),
    ]
