# Generated by Django 4.2.7 on 2023-12-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('employee_id', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_surname', models.CharField(max_length=100)),
                ('employee_hire_date', models.CharField(max_length=100)),
                ('employee_dni', models.CharField(db_column='employee_DNI', max_length=100)),
                ('branch_id', models.IntegerField()),
            ],
            options={
                'db_table': 'empleado',
                'managed': False,
            },
        ),
    ]
