# Generated by Django 4.2.7 on 2023-11-30 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
        ('Tarjetas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id_cuenta', models.AutoField(primary_key=True, serialize=False)),
                ('saldo', models.FloatField()),
                ('fecha_creacion', models.DateField()),
                ('id_cliente', models.ForeignKey(db_column='id_cliente', on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
                ('id_tipo_cuenta', models.ForeignKey(db_column='id_tipo_cuenta', on_delete=django.db.models.deletion.CASCADE, to='Tarjetas.tarjeta')),
            ],
        ),
    ]
