# Generated by Django 4.2.7 on 2023-12-09 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=50)),
                ('customer_surname', models.CharField(max_length=50)),
                ('customer_dni', models.CharField(db_column='customer_DNI', max_length=50)),
                ('dob', models.DateField(blank=True, null=True)),
                ('tipo_cliente', models.CharField(blank=True, choices=[('CLASSIC', 'CLASSIC'), ('GOLD', 'GOLD'), ('BLACK', 'BLACK')], max_length=50, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
    ]
