# Generated by Django 4.2.7 on 2023-11-30 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cuentas', '__first__'),
        ('Direcciones', '__first__'),
        ('Empleados', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cuenta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id_cliente', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('dni', models.IntegerField()),
                ('telefono', models.IntegerField()),
                ('email', models.CharField(max_length=50)),
                ('fecha_nacimiento', models.DateField()),
                ('id_cuenta', models.ForeignKey(db_column='id_cuenta', on_delete=django.db.models.deletion.CASCADE, to='Cuentas.cuenta')),
                ('id_direccion', models.ForeignKey(db_column='id_direccion', on_delete=django.db.models.deletion.CASCADE, to='Direcciones.direccion')),
                ('id_empleado', models.ForeignKey(db_column='id_empleado', on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado')),
                ('tipo_cliente', models.ForeignKey(db_column='tipo_cliente', on_delete=django.db.models.deletion.CASCADE, to='Clientes.tipocliente')),
            ],
        ),
    ]
