# Generated by Django 4.2.7 on 2023-11-30 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjeta_number', models.CharField(max_length=50)),
                ('cvv', models.CharField(max_length=50)),
                ('issuance_date', models.CharField(max_length=50)),
                ('expiration_date', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Clientes.cliente')),
            ],
        ),
    ]
