# Generated by Django 4.2.7 on 2023-12-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjeta_number', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=100)),
                ('issuance_date', models.CharField(max_length=100)),
                ('expiration_date', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tarjetas',
                'managed': False,
            },
        ),
    ]
