# Generated by Django 4.2.7 on 2023-12-03 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tarjetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tarjeta',
            table='tarjeta',
        ),
    ]
