# Generated by Django 4.2.7 on 2023-11-30 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('loan_id', models.AutoField(primary_key=True, serialize=False)),
                ('loan_type', models.CharField(max_length=50)),
                ('loan_date', models.CharField(max_length=50)),
                ('loan_total', models.IntegerField()),
                ('customer_id', models.IntegerField()),
            ],
        ),
    ]
